# Generated by Django 5.2.7 on 2025-10-31 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Giving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('giving_type', models.CharField(choices=[('tithe', 'Tithe'), ('offering', 'Offering'), ('pledge', 'Pledge'), ('donation', 'Donation')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('method', models.CharField(default='Mobile Money', max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
